name: Proxy Telegram Checker
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        run: bash run_check.sh
      - name: Process Result
        run: python process.py
      - name: Commit & Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add clean_proxies.txt
          git diff --staged --quiet || git commit -m "Update Telegram proxies"
          git push
